modLoader="javafml"
loaderVersion="[47,)"
license="MIT"
showAsResourcePack=false

[[mods]]
modId="nodead"
namespace="nodead"
version="1.0"
name="You can't dead!"
description="一个简单的模组，让玩家不会死亡！"
authors=["Aquavie"]
credits="Aquavie"
logoFile=""
updateJSONURL=""
displayURL=""
sourcesURL=""
screenshots=[]
displayTest="NONE"
issueTrackerURL=""

[[dependencies.nodead]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.nodead]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.20.2)"
ordering="NONE"
side="BOTH"